### ISSUE TITLE
Support `PrefixOp` expressions.

### ISSUE THREAD

**Issue by brech1** [namnc/circom-2-arithc#31]
Add support for the `PrefixOp` expression.

 - https://docs.circom.io/circom-language/basic-operators/#arithmetic-operators

**Comment by voltrevo** [comment]
@brech1 I have a [wip branch here](https://github.com/namnc/circom-2-arithc/pull/50) but I've run into some questions/issues:
1. Should new unary gates be supported in the output format? Or should we be compiling to the existing format somehow?
  a. Is the format specified somewhere?
3. How should `-x` (`ExpressionPrefixOpcode::Sub`) be handled? Should a `u32` underflow? Or perhaps emit a compilation error?

**Comment by brech1** [comment]
1. Thank you for bringing this up, so I think the supported gates are determined by our backend target, and so far in [mpz](https://github.com/tkmct/mpz/blob/a74cc6631aedaffa2921e2f0886fd6f351856043/mpz-circuits/src/arithmetic/components.rs#L91) these are available:

```
pub enum ArithGateType {
    /// Addition gate.
    Add,
    /// Subtraction gate.
    Sub,
    /// Multiplication gate.
    Mul,
    /// Constant multiplication gate.
    Cmul,
    /// Unary projection gate.
    Proj,
}
```
So perhaps we should update the gates we're supporting. This is also related to [this comment](https://hackmd.io/@brech1/circom-to-arithc-overview?comment=9121fdbd-40b4-4a05-9c8e-a314b11b0a38&utm_source=comment-card&utm_medium=icon) @namnc left in the overview. There is no defined format.

2. If an assignment to a gate is only `-x` I think it would be equal to `0 - x` so perhaps declaring a constant 0 as the other gate input for a subtraction gate. I think this and other cases should be handled individually in a new handle_prefix_op function, if it gets too long.

**Comment by namnc** [comment]
For simplicity let's (for now) stick to binary gate and have x = 0 - x for negation.

**Comment by namnc** [comment]
Point 2 is another issue itself. Rigft now we consider only u32 (behind the scene we do wraparound so -p becomes M-P with M being the bound of the value) but we should also consider i32? This is related to typing.

**Comment by brech1** [comment]
> For simplicity let's (for now) stick to binary gate and have x = 0 - x for negation.

And what should we do regarding the amount of gates we're supporting (more than the supported by the backend)? Should the backend handle this? Perhaps MP-SPDZ have a broader support?

> Point 2 is another issue itself. Rigft now we consider only u32 (behind the scene we do wraparound so -p becomes M-P with M being the bound of the value) but we should also consider i32? This is related to typing.

Even if we add the i32 type we have to handle overflows and underflows on unsigned. We could add a configurable `mod` integer so we can implement modular arithmetic with it, this would only be applied on integer operations.

**Comment by voltrevo** [comment]
https://github.com/namnc/circom-2-arithc/pull/50

**Comment by namnc** [comment]
The PrefixOp does not seem to be consistent with the InfixOp's behavior due to potential signal name reusage: 
e.g. given a and b that are signals, writing a += b is equivalent to a <== a + b, but we shouldn't have this in circom.

We can do either:
1. allow only this for variables
2. define a proper scheme to support signal name reusage in circom (this is a circom extension)

**Comment by voltrevo** [comment]
@namnc I'm confused, what does `a += b` have to do with prefix ops?

**Comment by namnc** [comment]
![image](https://github.com/namnc/circom-2-arithc/assets/1717146/c239f544-28b9-4187-a195-6608e20a5248)

yeah may be you are right lets make a separate issue for this, my bad
