### ISSUE TITLE
Avoid collisions in random signal id generation.

### ISSUE THREAD

**Issue by brech1** [namnc/circom-2-arithc#33]
We may face signal ids collisions on large circuits.

**Comment by namnc** [comment]
I have some thoughts on this:
- We have collision in u32 id even when the final circuit is 27k gate -> less than 100k vars, may be we can just do incremental id to remove collision, cost is to maintain one u32 inside memory, there should be no security concern with this way of id generation
- with point above, is u128 or even u128 necessary? (u32 already 4 billions) can we check the blowup factor for id in parsing circom program? (i.e. the number of var/signal ids divided by the node ids)
- we can consider larger id size for larger circuit (like when we really need u64 or u128) but maybe making this configurable is better

**Comment by brech1** [comment]
Yeah we could try incremental. The main reason I didn't went that way is because we need a mutable pointer to the top most runtime and it has to be passed around everywhere (even to the signal creation methods), but also thought it could be problematic with context branching and merging. 

I went with u128 because of the faster implementation, but it's true we're using more memory when it's not optimal and thought this was needed fast (for benchmarking 0.0.9).

I can try to implement this and see what issues come up!

**Comment by brech1** [comment]
Resolved in #40
